### ISSUE TITLE
the attention module is loss

### ISSUE THREAD

**Issue by wanzhixiao** [shurexiyue/ST-CGA#1]
thank you for your excellent work and i want to reproduce the experiment.
As descript in title,when run main.py ,raise the following 

Traceback (most recent call last):
  File "D:/pycharm/November/ST-CGA/main.py", line 1, in <module>
    import models
  File "D:\pycharm\November\ST-CGA\models.py", line 12, in <module>
    import attention
ModuleNotFoundError: No module named 'attention'

config_path="data.json",this file is also missing

**Comment by wanzhixiao** [comment]
where is the self attention moudle?

**Comment by jbdj-star** [comment]
The module of self attention is placed before GAT. Some modules and data of this work are used in the operation of the company, which is inconvenient to open. It will be updated after the confidentiality period. I'm sorry to have caused you some trouble. Thank you for your attention.
